//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Error {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Error() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Error", typeof(Error).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added Successfully.
        /// </summary>
        internal static string AddedSuccessfully {
            get {
                return ResourceManager.GetString("AddedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An update request is under review.
        /// </summary>
        internal static string Anupdaterequestisunderreview {
            get {
                return ResourceManager.GetString("Anupdaterequestisunderreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select your country..
        /// </summary>
        internal static string CountryRequired {
            get {
                return ResourceManager.GetString("CountryRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course was not found..
        /// </summary>
        internal static string Course_with_the_given_ID_was_not_found_ {
            get {
                return ResourceManager.GetString("Course with the given ID was not found.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must enter OTP.
        /// </summary>
        internal static string DecryptionKeyRequired {
            get {
                return ResourceManager.GetString("DecryptionKeyRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select or enter your department..
        /// </summary>
        internal static string DepartmentRequired {
            get {
                return ResourceManager.GetString("DepartmentRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Already Exist.
        /// </summary>
        internal static string EmailAlreadyExist {
            get {
                return ResourceManager.GetString("EmailAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter an email address.
        /// </summary>
        internal static string EmailIsRequired {
            get {
                return ResourceManager.GetString("EmailIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Length Not Valid.
        /// </summary>
        internal static string EmailLengthNotValid {
            get {
                return ResourceManager.GetString("EmailLengthNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email not found.
        /// </summary>
        internal static string EmailNotFound {
            get {
                return ResourceManager.GetString("EmailNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select or enter your Faculty.
        /// </summary>
        internal static string facultyRequired {
            get {
                return ResourceManager.GetString("facultyRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id Required.
        /// </summary>
        internal static string IdRequired {
            get {
                return ResourceManager.GetString("IdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid email address.
        /// </summary>
        internal static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email should be in the following format: test@test.com.
        /// </summary>
        internal static string InvalidEmailFormat {
            get {
                return ResourceManager.GetString("InvalidEmailFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email max lenght  is 100 .
        /// </summary>
        internal static string InvalidEmailMaxlength100 {
            get {
                return ResourceManager.GetString("InvalidEmailMaxlength100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Email or Password.
        /// </summary>
        internal static string InvalidEmailOrPass {
            get {
                return ResourceManager.GetString("InvalidEmailOrPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email or password.
        /// </summary>
        internal static string InvalidLogin {
            get {
                return ResourceManager.GetString("InvalidLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Mobile Number.
        /// </summary>
        internal static string InvalidMobileNumber {
            get {
                return ResourceManager.GetString("InvalidMobileNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plesae enter correct name.
        /// </summary>
        internal static string InvalidName {
            get {
                return ResourceManager.GetString("InvalidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid OTP.
        /// </summary>
        internal static string InvalidOTP {
            get {
                return ResourceManager.GetString("InvalidOTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be at least 8 characters long and include a mix of letters, numbers, and special characters.
        /// </summary>
        internal static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد الحروف 24.
        /// </summary>
        internal static string Length24 {
            get {
                return ResourceManager.GetString("Length24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max length is 150.
        /// </summary>
        internal static string MaximumLength150 {
            get {
                return ResourceManager.GetString("MaximumLength150", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Length 2500.
        /// </summary>
        internal static string MaximumLength2500 {
            get {
                return ResourceManager.GetString("MaximumLength2500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max length is 300.
        /// </summary>
        internal static string MaximumLength300 {
            get {
                return ResourceManager.GetString("MaximumLength300", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Length is 100.
        /// </summary>
        internal static string MaxLength100 {
            get {
                return ResourceManager.GetString("MaxLength100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Length 150.
        /// </summary>
        internal static string MaxLength150 {
            get {
                return ResourceManager.GetString("MaxLength150", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحد الأقصى 20 رقم .
        /// </summary>
        internal static string MaxLength20 {
            get {
                return ResourceManager.GetString("MaxLength20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the allowed max length 200.
        /// </summary>
        internal static string MaxLength200 {
            get {
                return ResourceManager.GetString("MaxLength200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Length 24 char.
        /// </summary>
        internal static string MaxLength24 {
            get {
                return ResourceManager.GetString("MaxLength24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Length 4.
        /// </summary>
        internal static string MaxLength4 {
            get {
                return ResourceManager.GetString("MaxLength4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Length 5.
        /// </summary>
        internal static string MaxLength5 {
            get {
                return ResourceManager.GetString("MaxLength5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Length 8.
        /// </summary>
        internal static string MaxLength8 {
            get {
                return ResourceManager.GetString("MaxLength8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min Length 2.
        /// </summary>
        internal static string MinLength2 {
            get {
                return ResourceManager.GetString("MinLength2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be at least 8 characters.
        /// </summary>
        internal static string MinLength8 {
            get {
                return ResourceManager.GetString("MinLength8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Number Already Exist.
        /// </summary>
        internal static string MobileNumberAlreadyExist {
            get {
                return ResourceManager.GetString("MobileNumberAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Number is Required.
        /// </summary>
        internal static string MobileNumberIsRequired {
            get {
                return ResourceManager.GetString("MobileNumberIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid mobile number..
        /// </summary>
        internal static string MobileNumberLengthNotValid {
            get {
                return ResourceManager.GetString("MobileNumberLengthNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Number Not Valid.
        /// </summary>
        internal static string MobileNumberNotValid {
            get {
                return ResourceManager.GetString("MobileNumberNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid mobile number..
        /// </summary>
        internal static string MobileRequired {
            get {
                return ResourceManager.GetString("MobileRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name Length Not Valid.
        /// </summary>
        internal static string NameLengthNotValid {
            get {
                return ResourceManager.GetString("NameLengthNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name Required.
        /// </summary>
        internal static string NameRequired {
            get {
                return ResourceManager.GetString("NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments should not exceed 250 characters..
        /// </summary>
        internal static string NoteLength {
            get {
                return ResourceManager.GetString("NoteLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTP Is Required.
        /// </summary>
        internal static string OTPIsRequired {
            get {
                return ResourceManager.GetString("OTPIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTP Length Not Valid.
        /// </summary>
        internal static string OtpLengthNotValid {
            get {
                return ResourceManager.GetString("OtpLengthNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTP Not Found.
        /// </summary>
        internal static string OTPNotFound {
            get {
                return ResourceManager.GetString("OTPNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords do not match..
        /// </summary>
        internal static string Passworddoesnotmatch {
            get {
                return ResourceManager.GetString("Passworddoesnotmatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Required.
        /// </summary>
        internal static string PasswordRequired {
            get {
                return ResourceManager.GetString("PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pasword Required.
        /// </summary>
        internal static string PaswordRequired {
            get {
                return ResourceManager.GetString("PaswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid email address.
        /// </summary>
        internal static string PleaseEnterEmail {
            get {
                return ResourceManager.GetString("PleaseEnterEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى إدخال الاسم الأول.
        /// </summary>
        internal static string PleaseEnterFirstName {
            get {
                return ResourceManager.GetString("PleaseEnterFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your last name.
        /// </summary>
        internal static string PleaseEnterLastName {
            get {
                return ResourceManager.GetString("PleaseEnterLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Retry After {0} min.
        /// </summary>
        internal static string PleaseTryAfter_0_ {
            get {
                return ResourceManager.GetString("PleaseTryAfter{0}", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have exhausted attempts to resend otp . Please wait for the specified time and try again later.
        /// </summary>
        internal static string ResendOTPMustBeAfterMinutes {
            get {
                return ResourceManager.GetString("ResendOTPMustBeAfterMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email already in use, please log in.
        /// </summary>
        internal static string ThisEmailAlerdyFound {
            get {
                return ResourceManager.GetString("ThisEmailAlerdyFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هذا الحقل إلزامي.
        /// </summary>
        internal static string ThisFeildRequired {
            get {
                return ResourceManager.GetString("ThisFeildRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Item Exit.
        /// </summary>
        internal static string ThisItemExit {
            get {
                return ResourceManager.GetString("ThisItemExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title is already exist.
        /// </summary>
        internal static string TitleAlreadyExist {
            get {
                return ResourceManager.GetString("TitleAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select or enter your university..
        /// </summary>
        internal static string UniversityRequired {
            get {
                return ResourceManager.GetString("UniversityRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify Pasword Required.
        /// </summary>
        internal static string VerifyPaswordRequired {
            get {
                return ResourceManager.GetString("VerifyPaswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid code, please try again.
        /// </summary>
        internal static string WrongOTP {
            get {
                return ResourceManager.GetString("WrongOTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong Password.
        /// </summary>
        internal static string WrongPassword {
            get {
                return ResourceManager.GetString("WrongPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Are Locked try after few minutes.
        /// </summary>
        internal static string YouAreLocked {
            get {
                return ResourceManager.GetString("YouAreLocked", resourceCulture);
            }
        }
    }
}
